idf_component_register(
    SRCS
        "main.c"
        "epd_ui.c"
        "bme280_sens.c"
        "bme280_mqtt.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_common
        esp_http_client
        cjson
        bmp280
        esp_driver_spi
        esp_driver_gpio
        esp_timer
    PRIV_REQUIRES mqtt
)
